# Generated by Django 4.2 on 2023-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Food', 'Food'), ('Pleasure', 'Pleasure'), ('Business', 'Business'), ('Gift', 'Gift')], max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
